{{- range $name, $service := $.Values.services }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-{{ $name }}
  labels:
    {{- include "common_labels" (dict "ServiceName" $name "Service" . "Root" $) | nindent 4 }}
  {{- if .deploy }}
  {{- if index .deploy "x-aws-iam-role-arn" }}
  annotations:
    eks.amazonaws.com/role-arn: {{ index .deploy "x-aws-iam-role-arn" }}
  {{- end }}
  {{- end }}
---
{{- end }}