services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - "6379"
  db:
    image: postgres:9.6
    ports:
      - "5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  vote:
    image: dockersamples/examplevotingapp_vote:before
    ports:
      - target: 80
        published: 80
        x-ingress:
          hosts:
            - vote.localhost
          paths:
            - /
          cert_issuer: letsencrypt
    deploy:
      replicas: 2
  result:
    image: dockersamples/examplevotingapp_result
    ports:
      - target: 80
        published: 80
        x-ingress:
          hosts:
            - results.localhost
          paths:
            - /
    deploy:
      replicas: 1
  worker:
    image: mikesir87/votingapp-worker
    deploy:
      replicas: 2
