{{- range $name, $service := $.Values.services }}
{{- if .expose }}
apiVersion: v1
kind: Service
metadata: 
  name: {{ $name }}
  labels:
    {{- include "common_labels" (dict "ServiceName" $name "Service" . "Root" $) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- range $port := .expose }}
    - port: {{ $port }}
      targetPort: {{ $port }}
    {{- end }}
  selector:
    {{- include "selector_labels" (dict "ServiceName" $name "Service" . "Root" $) | nindent 4 }}
---
{{- end }}
{{- end }}